# Generated by Django 5.2.6 on 2025-10-10 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Hassanue')),
            ],
        ),
        migrations.AlterModelOptions(
            name='airline',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.TextField(verbose_name='Название рейса'),
        ),
        migrations.AddField(
            model_name='airline',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.flight'),
        ),
    ]
