# Generated by Django 5.2.6 on 2025-10-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_flight_alter_airline_options_alter_airline_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='airline_name',
            field=models.TextField(null=True, verbose_name='Название авиакомпании'),
        ),
    ]
