# Generated by Django 5.2.6 on 2025-10-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_airline_airline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airline_name',
        ),
    ]
