# Generated by Django 5.2.6 on 2025-10-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0005_passengers_rate_alter_flight_options_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='passport',
            field=models.TextField(null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='name',
            field=models.TextField(verbose_name='ФИО пассажира'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.TextField(verbose_name='Тариф'),
        ),
    ]
