# Generated by Django 5.2.6 on 2025-10-17 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_passengers_passport_alter_passengers_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='tickets',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='tickets',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.flight'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.passengers'),
        ),
    ]
