# Generated by Django 5.2.6 on 2025-10-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0007_rename_tickets_tickets_rate_tickets_flight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО пассажира')),
                ('passport', models.CharField(max_length=20, verbose_name='Паспорт')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='rate',
        ),
        migrations.AlterModelOptions(
            name='airline',
            options={'verbose_name': 'Авиакомпания', 'verbose_name_plural': 'Авиакомпании'},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.RemoveField(
            model_name='airline',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.airline', verbose_name='Авиакомпания'),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.CharField(blank=True, max_length=100, verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='rate',
            name='multiplier',
            field=models.FloatField(default=1.0, verbose_name='Коэффициент цены'),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Авиакомпания'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(blank=True, max_length=5, verbose_name='Место')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата брони')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.flight', verbose_name='Рейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.passenger', verbose_name='Пассажир')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.rate', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
        migrations.DeleteModel(
            name='Passengers',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
