# Generated by Django 5.2.6 on 2025-10-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0008_passenger_remove_tickets_passenger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='picture',
            field=models.ImageField(null=True, upload_to='airline', verbose_name='Изображение'),
        ),
    ]
