# Generated by Django 5.2.6 on 2025-10-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_airline_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='picture',
            field=models.ImageField(null=True, upload_to='passengers', verbose_name='Изображение'),
        ),
    ]
