# Generated by Django 5.2.6 on 2025-11-03 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0011_passenger_user_ticket_user_alter_passenger_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время прилета'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время вылета'),
        ),
    ]
