# Generated by Django 5.2.6 on 2025-11-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0012_flight_arrival_time_flight_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
